version: '3'
services:
  redu-gnps2-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redu-gnps2-web
    volumes:
      - ./logs:/app/logs:rw
      - ./database:/app/database:rw
      - ./workflows:/app/workflows:rw
    ports:
    - "5000:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: template.ucsd.edu
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: template.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu


networks:
  nginx-net:
    external:
      name: nginx-net